workflows:
  ionic_android_web_build:
    name: Build Ionic Angular App for Android and Web
    environment:
      node: 20.0                       # Node.js >= 18.19
      java: 17
      android: true
      vars:
        PACKAGE_NAME: "com.medikamentenrechner.app"    # Passe ggf. an
    scripts:
      # --- Setup-Schritt: Android Permissions checken
      - name: Ensure gradlew is executable
        script: chmod +x android/gradlew

      # --- Dependencies installieren
      - name: Install npm dependencies
        script: npm ci

      # --- App builden: Web
      - name: Build Ionic Angular Web
        script: npx ionic build --prod

      # --- App builden: Android
      - name: Build Ionic Angular Android
        script: |
          npx ionic cap sync android
          cd android
          ./gradlew assembleRelease

    artifacts:
      - www/**
      - android/app/build/outputs/**/*.apk

    cache:
      cache_paths:
        - ~/.npm
        - node_modules 