workflows:
  medcalc-app:
    name: "KinderSpital Medikamentenrechner"
    max_build_duration: 45
    environment:
      vars:
        IONIC_ENV: "production"
      node: 18.16.0
      npm: 8.19.2
      xcode: latest
      groups:
        - google_play
        - app_store
    scripts:
      - name: Install Dependencies
        script: |
          npm install -g @ionic/cli
          npm ci
      - name: Build Ionic Web
        script: |
          ionic build --prod
      - name: Sync Capacitor
        script: |
          npx cap sync
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
      # Web-Artifacts (optional)
      - name: Export Web Build
        script: |
          mkdir -p $CM_BUILD_ARTIFACTS/web
          cp -R www/* $CM_BUILD_ARTIFACTS/web/
      # iOS Build (nur bei Mac-Builds)
      - name: Build iOS Release
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -archivePath $HOME/output/App.xcarchive archive
    artifacts:
      - android/app/build/outputs/**/*.apk
      - ios/build/**/*.ipa
      - $CM_BUILD_ARTIFACTS/web/**

    publishing:
      email:
        recipients:
          - sandro.meier@buhlergroup.com
