workflows:
  ionic_ios_build:
    name: Build Ionic Angular App for iOS (No Credentials)
    environment:
      node: 20.0
      java: 17
      xcode: 15.0
    scripts:
      - name: Install npm dependencies
        script: npm ci

      - name: Build Ionic Web (für iOS Assets)
        script: npx ionic build

      - name: Sync iOS code
        script: npx cap sync ios

      - name: Install iOS CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Build iOS (unsigned)
        script: |
          cd ios/App
          xcodebuild -scheme App -workspace App.xcworkspace -configuration Release -derivedDataPath build -sdk iphoneos CODE_SIGNING_ALLOWED=NO

    artifacts:
      - ios/App/build/Build/Products/Release-iphoneos/*.app

    cache:
      cache_paths:
        - ~/.npm
        - node_modules
